# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cob', models.CharField(max_length=8)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=20)),
                ('last_close', models.FloatField(default=0)),
            ],
        ),
    ]
