# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cob', models.CharField(max_length=8)),
                ('status', models.CharField(default='STARTED', max_length=10)),
                ('runtime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='summaryreport',
            name='cob',
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockscreener.ContextKey'),
            preserve_default=False,
        ),
    ]
