# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0002_auto_20181122_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextkey',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Started', max_length=10),
        ),
    ]
