# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0003_auto_20181123_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='d_perc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='high_52w',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='low_52w',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='ma_200d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='ma_30d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='ma_60d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='price_52w_perc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='price_band_52w',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='summaryreport',
            name='r_perc',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='summaryreport',
            name='last_close',
            field=models.FloatField(default=0, null=True),
        ),
    ]
